### ISSUE TITLE
Point marker on image

### ISSUE THREAD

**Issue by ArnauAlco** [blackary/streamlit-image-coordinates#18]
Hello, it's the first time I create a request, so forgive me if I'm not doing this properly.

Would it be possible to add a marker such as a circle or a little dot to the point selected on the image? 
If it's already done, where can I find the way to use it?

Thank you so much in advanced.

**Comment by blackary** [comment]
Yes, you can see an example here https://image-coordinates.streamlit.app/dynamic_update and the code here https://github.com/blackary/streamlit-image-coordinates/blob/main/pages/dynamic_update.py
