### ISSUE TITLE
Is it possible to only return the values without image display?

### ISSUE THREAD

**Issue by ozangungor12** [blackary/streamlit-image-coordinates#22]
Hello, thanks for the component!

I realized that when I use the component it adds a new image visualization to my app, but I already have my page layout and visualizations defined, is it possible to only retrieve the values from the component, without adding the visualization?

Thanks!

**Comment by blackary** [comment]
Do you mean to have a separate image in your app, just using st.image or something similar, and get the coordinates clicked on that image if this component is installed?

Unfortunately, you have to get the coordinates from the image displayed by this app, and can't get them from a different component.

**Comment by ozangungor12** [comment]
Thank you for the clarification! Yes, I wanted to get the coordinates from an already displayed image.
