### ISSUE TITLE
Add use_container_width argument

### ISSUE THREAD

**Issue by blackary** [blackary/streamlit-image-coordinates#3]

**Comment by aditya47b** [comment]
Add use_container_width argument in streamlit_image_coordinates method it would be so useful

**Comment by epizzigoni** [comment]
👍 +1 on this! It would be super useful!

**Comment by JoelDJ2002** [comment]
yes I don't want to use that white iframe . Would be great if there is option for that feature be removed

**Comment by cfowle** [comment]
+1 on this! Could definitely use this feature :)

**Comment by blackary** [comment]
Closed by #13
