### ISSUE TITLE
X2 Y2 Coordinate

### ISSUE THREAD

**Issue by thecourtchart** [blackary/streamlit-image-coordinates#9]
I'm coming from Streamlit community page and want to ask about a new feature to do with these components. I just wonder, can I make it so the coordinate becomes X X2 Y Y2? X2 and Y2 in here are the results of action when we click-drag the cursor in the image area and record the last position once we let go the drag. This will be so helpful if I want to use it to record an action event of Football Match. Thank you!

**Comment by blackary** [comment]
Solved by #14
